name: NoDupeIP
version: 0.2
description: Disallows the same IP to join as another user.
author: ThaPengwin
website: http://thapengwin.tk/
main: tk.thapengwin.NoDupeIP.NoDupeIP
commands:
  IP:
    description: Checks the player's IP address.
    usage: /ip [player]
    permission: NoDupeIP.checkip
    permission-message: You do not have permission.
  NoDupeIP:
    description: NoDupeIP main command
    usage: /NoDupeIP
    permission: NoDupeIP.admin
    permission-message: You do not have permission.
     
permissions:
  NoDupeIP.checkip:
    description: Allows the player to use /ip
    default: op
  NoDupeIP.admin:
    description: Allows the player to use /NoDupeIP
    default: op
  NoDupeIP.notify:
    description: Notifies the player when somebody tries to join with a changed username.
    default: op